# Generated by Django 2.2.12 on 2020-05-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('account', models.CharField(max_length=20, verbose_name='帳號')),
                ('password', models.CharField(max_length=20, verbose_name='密碼')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tel', models.CharField(max_length=20, verbose_name='電話')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
            ],
            options={
                'db_table': '老闆',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DataSheet',
            fields=[
                ('buBien1', models.CharField(help_text='布邊x/穿筘x根入/x根', max_length=30, verbose_name='布邊1')),
                ('buBien2', models.CharField(help_text='布邊x/穿筘x根入/x根', max_length=30, verbose_name='布邊2')),
                ('buSien', models.CharField(help_text='布邊x/穿筘x根入/x根', max_length=30, verbose_name='布身')),
                ('weiMi', models.CharField(help_text='根/吋', max_length=20, verbose_name='機上緯密')),
                ('koFu', models.CharField(help_text='寸', max_length=10, verbose_name='筘幅')),
                ('length', models.CharField(help_text='y', max_length=10, verbose_name='整經長')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orderFormID', models.CharField(max_length=20, verbose_name='訂單ID')),
                ('progress', models.CharField(max_length=100, verbose_name='進度')),
                ('staffID', models.CharField(max_length=10, verbose_name='員工ID')),
                ('IDName', models.CharField(max_length=10, verbose_name='規格單ID')),
                ('arrangement', models.CharField(max_length=100, verbose_name='經紗排列')),
                ('sewingMethod', models.CharField(max_length=100, verbose_name='穿法')),
            ],
            options={
                'db_table': '規格單',
                'ordering': ['IDName'],
            },
        ),
        migrations.CreateModel(
            name='OrderForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('IDName', models.CharField(max_length=20, verbose_name='訂單ID')),
                ('hasReceivedCash', models.CharField(help_text='1/0', max_length=2, verbose_name='收費')),
                ('hasShipped', models.CharField(help_text='1/0', max_length=2, verbose_name='出貨')),
                ('deadLine', models.CharField(help_text='2020/12/12', max_length=10, verbose_name='期限')),
                ('firmName', models.CharField(max_length=20, verbose_name='廠商名字')),
                ('dateReceived', models.CharField(help_text='2020/12/12', max_length=10, verbose_name='接單日期')),
            ],
            options={
                'db_table': '訂單',
                'ordering': ['IDName'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('account', models.CharField(max_length=20, verbose_name='帳號')),
                ('password', models.CharField(max_length=20, verbose_name='密碼')),
                ('gender', models.CharField(max_length=6, verbose_name='性別')),
                ('birthdate', models.CharField(help_text='2020/12/12', max_length=10, verbose_name='出生年月日')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=20, verbose_name='地址')),
                ('tel', models.CharField(max_length=20, verbose_name='電話')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('IDName', models.CharField(max_length=10, verbose_name='員工ID')),
            ],
            options={
                'db_table': '員工',
                'ordering': ['IDName'],
            },
        ),
    ]
