# Generated by Django 3.0 on 2020-06-08 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlineOrderSystem', '0002_orderform_datasheetid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasheet',
            name='orderFormID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineOrderSystem.OrderForm'),
        ),
        migrations.AlterField(
            model_name='datasheet',
            name='staffID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='onlineOrderSystem.Staff'),
        ),
    ]
